/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


public class Datos_Medicos extends javax.swing.JFrame {
public static List<String[]> datosConsultas = new ArrayList<>();
    
    public Datos_Medicos() {
   
        initComponents();
        this.setLocationRelativeTo(null);
         llenarComboBoxMedicos();
         llenarComboBoxEspecialidades();
         llenarComboBoxHoras();
    }
    private String nombreMedicoSeleccionado;
    private String nombrePacienteIngresado;
    private String especialidadMedicoSeleccionada;
    private String horasDisponiblesSeleccionadas;
    
    
    
    private void llenarComboBoxMedicos() {
        // Datos específicos para el JComboBox de Médicos
        String[] datosMedicos = {"Juan Meza", "Pedro Pascal", "Juan Fernandez"};
        NomMed.setModel(new DefaultComboBoxModel<>(datosMedicos));
    }
    
    private void llenarComboBoxEspecialidades() {
        // Datos específicos para el JComboBox de Especialidades
        String[] datosEspecialidades = {"Medicina General", "Traumatología", "Pediatría"};
        EspecialidadMed.setModel(new DefaultComboBoxModel<>(datosEspecialidades));
    }

    private void llenarComboBoxHoras() {
        // Datos específicos para el JComboBox de Horas Disponibles
        String[] datosHoras = {"8:00 AM", "10:00 AM", "2:00 PM","4:00"};
        HorasDispo.setModel(new DefaultComboBoxModel<>(datosHoras));
    //////////////////////////////////////////////////////////////////////

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomPac = new javax.swing.JTextField();
        NomMed = new javax.swing.JComboBox<>();
        EspecialidadMed = new javax.swing.JComboBox<>();
        HorasDispo = new javax.swing.JComboBox<>();
        Aceptar_Datos = new javax.swing.JButton();
        Cancelar_Datos = new javax.swing.JButton();
        Nombre_Medico = new javax.swing.JLabel();
        Nombre_Paciente = new javax.swing.JLabel();
        Especialidad_Medico = new javax.swing.JLabel();
        Horas_Disponibles = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomPacActionPerformed(evt);
            }
        });

        NomMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NomMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomMedActionPerformed(evt);
            }
        });

        EspecialidadMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        HorasDispo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Aceptar_Datos.setText("Aceptar");
        Aceptar_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar_DatosActionPerformed(evt);
            }
        });

        Cancelar_Datos.setText("Cancelar");
        Cancelar_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_DatosActionPerformed(evt);
            }
        });

        Nombre_Medico.setText("Nombre del Médico :");

        Nombre_Paciente.setText("Nombre del Paciente :");

        Especialidad_Medico.setText("Especialidad :");

        Horas_Disponibles.setText("Horas Disponibles :");

        jLabel5.setText("Valor Hora : $7.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_Medico)
                            .addComponent(Nombre_Paciente)
                            .addComponent(Especialidad_Medico)
                            .addComponent(Horas_Disponibles))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HorasDispo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NomMed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NomPac)
                            .addComponent(EspecialidadMed, 0, 125, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Aceptar_Datos)
                        .addGap(60, 60, 60)
                        .addComponent(Cancelar_Datos)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Medico)
                    .addComponent(NomMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_Paciente)
                    .addComponent(NomPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Especialidad_Medico)
                    .addComponent(EspecialidadMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Horas_Disponibles)
                    .addComponent(HorasDispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar_Datos)
                    .addComponent(Aceptar_Datos))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancelar_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_DatosActionPerformed
      Seleccion newframe=new Seleccion();
      newframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cancelar_DatosActionPerformed

    private void Aceptar_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar_DatosActionPerformed

     
     
     
    nombreMedicoSeleccionado = NomMed.getSelectedItem().toString();
    nombrePacienteIngresado = NomPac.getText();
    especialidadMedicoSeleccionada = EspecialidadMed.getSelectedItem().toString();
    horasDisponiblesSeleccionadas = HorasDispo.getSelectedItem().toString();

    // Crear una cadena con los datos seleccionados
    String datosSeleccionados = "Médico: " + nombreMedicoSeleccionado +
                                ", Paciente: " + nombrePacienteIngresado +
                                ", Especialidad: " + especialidadMedicoSeleccionada +
                                ", Hora: " + horasDisponiblesSeleccionadas;
     
     String[] datosConsulta = {
            nombreMedicoSeleccionado,
            nombrePacienteIngresado,
            especialidadMedicoSeleccionada,
            horasDisponiblesSeleccionadas
             
        };
     datosConsultas.add(datosConsulta);
    
     MensajeFinal mensajeFinal = new MensajeFinal(nombreMedicoSeleccionado, nombrePacienteIngresado,
                                                 especialidadMedicoSeleccionada, horasDisponiblesSeleccionadas);
    
    // Mostrar el frame MensajeFinal
    mensajeFinal.setVisible(true);

    
    dispose();
     
     
   
    }//GEN-LAST:event_Aceptar_DatosActionPerformed

    private void NomPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomPacActionPerformed
        
    }//GEN-LAST:event_NomPacActionPerformed

    private void NomMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomMedActionPerformed
String[] datos = {};
        JComboBox<String> comboBox = new JComboBox<>(datos);
    }//GEN-LAST:event_NomMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos_Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos_Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos_Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos_Medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos_Medicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar_Datos;
    private javax.swing.JButton Cancelar_Datos;
    private javax.swing.JComboBox<String> EspecialidadMed;
    private javax.swing.JLabel Especialidad_Medico;
    private javax.swing.JComboBox<String> HorasDispo;
    private javax.swing.JLabel Horas_Disponibles;
    private javax.swing.JComboBox<String> NomMed;
    private javax.swing.JTextField NomPac;
    private javax.swing.JLabel Nombre_Medico;
    private javax.swing.JLabel Nombre_Paciente;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
